devchat-ai/devchat-vscode

- media/actionButton.js
- media/chatPanel.html
- media/chatUI.js
- media/codeBlock.js
- media/contextMenu.js
- media/inputContainer.js
- media/main.js
- media/markdown.js
- media/messageContainer.js
- media/messageUtil.js
Refactor code to have more better modularity.
> Commit message command

- src/commandManager.ts
- src/exampleCommand1.ts
- src/exampleCommand2.ts
- src/loadCommands.ts
- src/messageHandler.ts
- tsconfig.json
Support command extension. Add two example commands.
> Support commands extension

- src/commandManager.ts
- src/commitMessageCommand.ts
- src/commitMessageCommandInstructions.txt
- src/commonInstructions.txt
- src/devchat.ts
- src/exampleCommand1.ts
- src/exampleCommand2.ts
- src/loadCommands.ts
- src/messageHandler.ts
> Command commit message

- src/dtm.ts
- src/extension.ts
- src/messageHandler.ts
new message:
{
command: 'doCommand',
content: 'commit message'
}
> add doCommit message

- media/chatPanel.css
- media/chatPanel.html
- media/inputContainer.js
- src/contextManager.ts
- src/exampleContext.ts
- src/loadContexts.ts
- src/messageHandler.ts
Add context by menu. We need more work to implement different contexts.
> add context by menu

- src/commitMessageCommand.ts
- src/commonUtil.ts
- src/contextCodeSelected.ts
- src/contextCustomCommand.ts
- src/contextFileSelected.ts
- src/contextGitDiff.ts
- src/contextGitDiffCached.ts
- src/extension.ts
- src/loadContexts.ts
- src/messageHandler.ts
1. add git diff context
2. add git diff --cached context
3. add file select context
4. add code select context
5. add custom command context
> add context implementation

- assets/clipboard.js
- src/applyCode.ts
- src/messageHandler.ts
> support diff view action

- package.json
- src/devchat.ts
Add open ai config items to vscode config system.
> Add config

- src/applyCode.ts
Support compare with selected code.
> add diff with selection

- src/views/ChatPanel.tsx
Add focus to input on load and new commands to command menu. Also, added new icons to the plus menu.
> feat: Add focus to input on load and new commands to command menu

- package.json
- src/toolwrapper/devchat.ts
Update to lastest devchat. Fix stream option doesn't work issue.
> update to lastest devchat

- src/context/contextCodeSelected.ts
- src/context/contextCustomCommand.ts
- src/context/contextFileSelected.ts
- src/context/contextGitDiff.ts
- src/context/contextGitDiffCached.ts
- src/context/contextRef.ts
- src/context/exampleContext.ts
- src/context/loadContexts.ts
- src/handler/addRefCommandContext.ts
- src/handler/contextDetail.ts
- src/handler/loadHandlers.ts
- src/util/commonUtil.ts
save context as json
support /ref command to context
support context detail message
> save context as json

- src/handler/contextDetail.ts
add file field for contextDetailResponse message
> add file field for contextDetailResponse message

- src/handler/sendMessage.ts
- src/toolwrapper/devchat.ts
fix parent hash error, we can use the history chat message as context now.
> fix parent hash error

- src/toolwrapper/dtm.ts
handle json parse exception in dtm runCommand.
> handle exception in dtm

- src/command/commitMessageCommand.ts
- src/context/contextCustomCommand.ts
- src/context/contextGitDiff.ts
- src/context/contextGitDiffCached.ts
- src/context/contextRef.ts
- src/contributes/util.ts
- src/extension.ts
- src/handler/addContext.ts
- src/handler/addRefCommandContext.ts
- src/handler/contextDetail.ts
- src/handler/convertCommand.ts
- src/handler/historyMessages.ts
- src/handler/messageHandler.ts
- src/handler/regCommandList.ts
- src/handler/regContextList.ts
- src/handler/sendMessage.ts
- src/init/chatConfig.ts
- src/toolwrapper/devchat.ts
- src/toolwrapper/dtm.ts
- src/util/logger.ts
> Log to vscode

- src/handler/sendMessage.ts
- src/toolwrapper/devchat.ts
- Import ChatResponse from DevChat in sendMessage.ts
- Update sendMessage function to handle parent_hash and partial responses
- Refactor DevChat.chat to parse response data and handle partial stdout
- Remove unused lastPromptHash variable
> Refactor sendMessage and improve DevChat response handling

- package.json
- src/toolwrapper/dtm.ts
package dtm in devchat-vscode.
> Package dtm

- package.json
- src/handler/historyMessages.ts
- src/toolwrapper/devchat.ts
Add configuration options for log count and skip
- Added new configuration options in package.json for maxLogCount and logSkip
- Updated historyMessages.ts to handle the new configuration options
- Modified devchat.ts to use the new configuration options when fetching logs
> handle devchat log

- src/context/contextFileSelected.ts
- src/contributes/util.ts
- src/extension.ts
- src/handler/addContext.ts
- src/handler/addRefCommandContext.ts
- src/handler/codeApply.ts
- src/handler/codeFileApply.ts
- src/handler/contextDetail.ts
- src/handler/convertCommand.ts
- src/handler/doCommit.ts
- src/handler/historyMessages.ts
- src/handler/listMessages.ts
- src/handler/loadHandlers.ts
- src/handler/messageHandler.ts
- src/handler/regCommandList.ts
- src/handler/regContextList.ts
- src/handler/sendMessage.ts
- src/handler/showDiff.ts
- src/panel/chatPanel.ts
- src/util/reg_messages.ts
> Secret branch

- package.json
- src/context/contextGitDiff.ts
- src/contributes/commands.ts
- src/toolwrapper/devchat.ts
> Check dependence

- src/views/ChatPanel.tsx
This commit adds the ability to commit code blocks with the commit message syntax highlighting. The commit button appears only when the code block is a commit message. The commit button sends the commit message content to the server. The commit button changes color to teal when the commit is successful.
> feat: Add commit functionality to code blocks

- src/views/ChatPanel.tsx
- Set message width to the width of the scroll viewport
- Set scroll area width to the width of the chat panel minus 2rem
> feat: Adjust width of chat panel messages and scroll area

- package.json
- src/contributes/commands.ts
- src/extension.ts
- src/toolwrapper/devchat.ts
1. Add command to set OPENAI_API_KEY;
2. Config devchat path;
3. Support Chinese/English menu items;
> Fix Issues

- src/contributes/commands.ts
- src/extension.ts
> Support status item action

- src/handler/historyMessages.ts
- src/handler/messageHandler.ts
If DevChat can't found OPENAI_API_KEY, then ask user to input the API key.
> Set api key in chat

- src/handler/doCommit.ts
- src/toolwrapper/dtm.ts
- src/util/commonUtil.ts
Commit all changes if no cached changes.
> add command to commit all changes

- src/util/appyDiff.ts
> Fix diff instructions

- package.json
- src/contributes/commands.ts
- src/extension.ts
- Bump package version from 0.0.34 to 0.0.38.
- Change pip3 install command to include --upgrade flag.
- Add check for DevChatPath configuration before setting status to ready.
> Update package version and improve installation process

- src/views/ChatPanel/index.tsx
- Change Flex to Stack for better message layout
- Add avatar and name to each message
- Increase padding and change background color for better readability
> refactor(chatpanel): improve message display

- src/views/ChatPanel/index.tsx
Changed the margin of the Flex component in ChatPanel to use shorthand CSS properties.
> Refactor ChatPanel Flex margin

- src/views/ChatPanel/index.tsx
Add border radius to Accordion and Menu components to improve the UI. Also, add specific styles to the active and expanded states of the components. The changes were made in src/views/ChatPanel/index.tsx.
> refactor: Add border radius to Accordion and Menu components

- src/views/ChatPanel/index.tsx
- Add 'xs' size to the button
- Set fontSize to 'var(--vscode-editor-font-size)'
> Update ChatPanel button style

- package-lock.json
- package.json
- src/toolwrapper/devchat.ts
- src/toolwrapper/dtm.ts
- src/util/commonUtil.ts
> replace dtm with git

- src/command/commandManager.ts
- src/command/customCommand.ts
- src/handler/showDiff.ts
- src/toolwrapper/devchat.ts
- src/util/appyDiff.ts
- workflows/code_actions/_setting_.json
- workflows/code_actions/instruct.txt
fix bugs to apply diff.
add /modify_actions command to  test diff.
> Refactor code

- src/handler/loadHandlers.ts
- src/handler/sendMessage.ts
1. handler user stop error
2. add regeneration message
> Support regeneration

- package.json
- src/extension.ts
- src/handler/historyMessages.ts
- src/handler/messageHandler.ts
- src/handler/sendMessage.ts
- src/panel/chatPanel.ts
- src/panel/devchatView.ts
- src/panel/webviewManager.ts
- src/toolwrapper/devchat.ts
- src/topic/loadTopics.ts
- src/topic/topicManager.ts
- src/util/messageHistory.ts
- Implement Topic and TopicManager classes.
- Add TopicTreeDataProvider and TopicTreeItem classes.
- Register new commands for topic management.
- Update package.json with new commands and dependencies.
> Add topic management features to DevChat extension

- src/extension.ts
- Replace "devchat_version_old" with "DevChatVersionOld".
- Update related variable names and function calls.
> Update key names in secretStorage

- src/extension.ts
- Added a new flag isVersionChangeCompare to prevent duplicate version checks.
- Updated the condition to check for version changes only when the flag is false.
> Add isVersionChangeCompare flag to extension.ts

- src/handler/historyMessages.ts
- src/handler/historyMessagesBase.ts
- src/util/messageHistory.ts
- Updated historyMessages to handle pagination with skip and maxCount.
- Exported LoadHistoryMessages interface from historyMessagesBase.
- Added setTopic and getTopic methods to messageHistory class.
- Implemented loadTopicHistoryFromCurrentMessageHistory function.
> Refactor historyMessages and historyMessagesBase

- src/handler/sendMessageBase.ts
- Update sendMessageBase.ts with the new function.
- Replace Date.parse with parseDateStringToTimestamp.
- Fix string comparison with strict equality.
> Add parseDateStringToTimestamp function

- src/handler/sendMessageBase.ts
- Remove unnecessary empty string check in sendMessageBase.ts.
- Simplify condition to only check for chatResponse.isError.
> Refactor handlerResponseText condition check

- src/context/contextManager.ts
- src/util/commonUtil.ts
- src/util/uiUtil.ts
- src/util/uiUtil_vscode.ts
- Add UiUtilWrapper.showErrorMessage() method in uiUtil.ts.
- Update contextManager.ts to display error messages using UiUtilWrapper.
- Refactor CommandRun error handling in commonUtil.ts.
- Implement showErrorMessage() in uiUtil_vscode.ts.
> Improve error handling and display in UI

- src/topic/topicManager.ts
- Added condition to check for currentTopicId.
- Updated currentTopicId to use firstMessageHash.
> Refactor topicManager.ts to use firstMessageHash

- src/views/ChatPanel/chatSlice.ts
- src/views/ChatPanel/index.tsx
- Removed messageUtil.sendMessage from chatSlice stopGenerating action.
- Added messageUtil.sendMessage to StopButton onClick event in ChatPanel index.tsx.
> Move stopDevChat message sending to StopButton onClick

- src/panel/statusBarViewBase.ts
- Corrected the assignment of versionChanged variable.
- Removed unnecessary const declaration.
> Fix versionChanged assignment in statusBarViewBase.ts

- src/views/InputMessage.tsx
- Modify event condition to include Tab key along with Enter key.
> Allow Tab key to select command in InputMessage

- src/contributes/commandsBase.ts
- src/panel/statusBarViewBase.ts
- src/util/commonUtil.ts
- Added a new optional parameter 'showError' in checkDevChatDependency function in commandsBase.ts.
- Updated the conditions for logging error messages in checkDevChatDependency function.
- Updated the call to checkDevChatDependency in dependencyCheck function in statusBarViewBase.ts to pass 'showError' parameter.
- Updated the condition for logging stderr in CommandRun class in commonUtil.ts.
> Refactor error handling and logging in DevChat dependency check

- src/contributes/commandsBase.ts
- src/util/uiUtil_vscode.ts
- tools/install.py
- Added version check for DevChat in checkDevChatDependency function.
- Updated configuration in both Global and Workspace scopes.
- Commented out the initial DevChat check in install.py and added --force flag to pip install command.
> Update DevChat dependency check and configuration update

- src/handler/sendMessageBase.ts
- src/topic/topicManager.ts
- Added a check in deleteChatMessageBase to remove the message from the current topic if deletion is successful.
- Modified updateFirstMessageHashAndName in Topic class to accept undefined values.
- Added a new method deleteMessage in TopicManager to update the topic when a message is deleted.
> Update message deletion and topic management

- src/action/symbolDefAction.ts
- src/action/symbolRefAction.ts
> Fix symbole ref error

- src/action/actionManager.ts
- src/action/currentDocumentAction.ts
- src/action/selectContextAction.ts
- Added CurrentDocumentAction and SelectContextAction to ActionManager.
- Created new files for CurrentDocumentAction and SelectContextAction.
- CurrentDocumentAction retrieves the current active document.
- SelectContextAction retrieves the selected information in the current document.
> Add CurrentDocumentAction and SelectContextAction

- src/action/actionManager.ts
- src/action/selectContextAction.ts
- src/action/symbolRefAction.ts
- src/contributes/commandsBase.ts
> Fix symbol ref bug

- tools/install.py
- Imported tempfile module to create a temporary file.
- Replaced the creation of 'test.txt' in the current directory with a temporary file.
- The temporary file is automatically deleted when it is closed, eliminating the need for manual deletion.
> Change location of temporary file in pip_cmd_run function

- src/handler/sendMessage.ts
- src/views/InputMessage.tsx
- src/views/chatSlice.ts
fix context file missed in history message
> Test fix 2

- src/action/symbolDefAction.ts
- src/action/symbolRefAction.ts
- Improved error handling and validation in symbol definition and reference retrieval functions.
- Enhanced the logic for finding the smallest symbol definition that contains the target range.
- Updated the function descriptions to provide more detailed information about their purpose, input, output, and error handling.
- Added 'ref_line' to the output of the symbol reference retrieval function.
> Refactor symbol definition and reference retrieval

- src/views/components/MessageHeader/index.tsx
- Added marginRight of 10px to the container holding the ActionIcon in MessageHeader.
- Also applied marginRight of 10px to the ActionIcon itself for consistent spacing.
> Adjust margin in MessageHeader component

- package.json
- Downgraded the required vscode version from ^1.77.0 to ^1.74.0 in package.json.
- Also updated the @types/vscode version to match the vscode version.
> Downgrade vscode version in package.json

- package.json
- Updated the vscode version from "^1.74.0" to "^1.75.0" in the engines section.
- Also updated the @types/vscode version from "^1.74.0" to "^1.75.0" in the dependencies section.
> Update vscode version in package.json

- tools/install.py
- Added a new function `get_app_data_dir` in `install.py` to get the application data directory based on the operating system.
- This function checks if the directory exists, if not, it creates the directory.
- Updated the `venvdir` in the `main` function to use this new function, which will now point to the application data directory.
> Add function to get application data directory

- src/action/actionManager.ts
- tools/install.py
Parse "Actual location" after create virtual env;
Check duplicated action.
> Fix python error

- tools/install.py
- Changed the regex match to search for bytes instead of string.
- Added a condition to decode the pythonCmd only if no error occurred.
> Fix regex match and decoding in install.py

- src/contributes/commands.ts
- src/contributes/commandsBase.ts
- src/panel/statusBarView.ts
- src/panel/statusBarViewBase.ts
- src/util/python_installer/app_install.ts
- src/util/python_installer/conda_install.ts
- src/util/python_installer/conda_url.ts
- src/util/python_installer/https_download.ts
- src/util/python_installer/install_askcode.ts
- src/util/python_installer/install_devchat.ts
- src/util/python_installer/package_install.ts
- src/util/python_installer/python_install.ts
- src/util/python_installer/readme.md
- test/contributes/commandsBase.test.ts
Install devchat and askcode by conda.
> Package python for windows

- workflows/auto_command/action/ask_codebase/handler.py
- Move the 'get_app_data_dir' function to the top of the file.
- Add comments to explain the purpose of the function.
- Initialize the 'supportedFileTypes' variable.
- Update the file path for 'STORAGE_FILE' to use the 'get_app_data_dir' function.
> Refactor handler.py

- src/panel/statusBarView.ts
- src/util/uiUtil_vscode.ts
- Refactored the createStatusBarItem function in statusBarView.ts to use vscode.window.withProgress for a better user experience.
- Added a progress indicator while checking the devchat dependency environment.
- Updated the status bar item text, tooltip, and command based on the dependency and API key status.
- Added error handling for any exceptions that occur during the dependency check.
- Updated the updateConfiguration function in uiUtil_vscode.ts to include error handling.
> Refactor status bar view and UI utility

- src/context/contextRefDefs.ts
- src/contributes/commands.ts
- src/panel/statusBarView.ts
- src/util/progressBar.ts
- src/util/python_installer/package_install.ts
Show progress for ask codebase indexing.
> Show askcodebase progress

- package.json
- src/contributes/commands.ts
- src/extension.ts
- tools/askcode_summary_index.py
- workflows/auto_command/action/summary/_setting_.json
- workflows/auto_command/action/summary/handler.py
- Added commands for adding context and summary to DevChat.
- Updated the package.json file to include the new commands.
- Added command handlers for indexing and describing codebase summaries.
- Created a new file, askcode_summary_index.py, for indexing and describing codebase summaries.
- Added a new setting file, _setting_.json, for the summary action in the auto_command workflow.
- Added a new handler file, handler.py, for the summary action in the auto_command workflow.
> Add commands for DevChat

- src/handler/sendMessage.ts
- Modified the sendMessage function in the sendMessage.ts file.
- Added code to clear the message.contextInfo property before sending the message.
> Clear contextInfo in sendMessage

- tools/askcode_summary_index.py
- Added a global dictionary 'g_file_need_index' to keep track of files that need indexing.
- Modified 'is_file_modified' function to print file paths of non-source code and hidden files.
- Refactored 'custom_file_filter' function to use 'g_file_need_index' for determining if a file needs indexing.
- Removed unnecessary print statements for cleaner output.
> Updated askcode_summary_index.py for better file indexing

- src/views/pages/ChatPanel.tsx
- src/views/stores/ChatStore.ts
- Imported additional components and icons in ChatPanel.tsx.
- Added a conditional button to the error message in ChatPanel.tsx that appears when the error message contains 'Insufficient balance'. This button directs the user to the official website to recharge.
- Added a new property 'rechargeSite' to the ChatStore model in ChatStore.ts.
> Add recharge link to chat error message

- src/views/components/MessageMarkdown/index.tsx
- src/views/stores/ChatStore.ts
- Added explanations for the /code, /commit_message, and /release_note commands in MessageMarkdown/index.tsx.
- Updated the helpMessage function in ChatStore.ts to include the explanations for the new commands.
- Updated the list of available commands in ChatStore.ts to reflect the changes.
> Add explanations for /code, /commit_message, and /release_note commands

- src/util/feature_flags/feature_toggles.ts
- Update the feature toggle for "ask-code" to true in the feature_toggles.ts file.
> Update feature toggle for "ask-code" to true

- src/views/pages/ChatPanel.tsx
- Reduced the minimum width of the chat panel from 310 to 300 for better layout.
- Adjusted the width of the chat panel to match the chatPanelWidth variable, improving consistency.
> Adjust minimum width and width of chat panel in ChatPanel component

- src/views/components/InputMessage/index.tsx
- Removed the commandMenuIcon function from InputMessage component.
- Updated the UI by removing the commandMenuIcon from the menu items.
- Added padding to the left of the menu items for better alignment.
> Remove commandMenuIcon function and update UI

- src/views/components/StopButton/index.tsx
- src/views/pages/ChatPanel.tsx
- src/views/stores/ChatStore.ts
- Changed the parameters of stopGenerating function to accept hash and message as strings.
- Updated the stopGenerating function calls in StopButton and ChatPanel components.
- Added a condition to update the last message when the generation has not completed.
> Refactor stopGenerating function in ChatStore

- package.json
- src/command/commandManager.ts
- src/contributes/commands.ts
- src/contributes/commandsBase.ts
- src/extension.ts
- src/handler/loadHandlers.ts
- src/handler/regCommandList.ts
- src/panel/statusBarView.ts
- src/toolwrapper/devchat.ts
- src/util/python_installer/package_install.ts
- src/views/components/InputMessage/index.tsx
- src/views/stores/InputStore.ts
Support command extension by "devchat run" command.
> Support devchat run

- src/context/contextDefRefs.ts
- src/context/contextRefDefs.ts
- src/contributes/commands.ts
Fix symbol defines context error.
> Update symbol define2

- src/context/contextCustomCommand.ts
- src/context/contextDefRefs.ts
- src/context/contextGitDiff.ts
- src/context/contextGitDiffCached.ts
- src/context/contextRefDefs.ts
- src/views/components/InputMessage/index.tsx
- workflows/default/context/git_log_for_releasenote/_setting_.json
I have two questions:
- @yangbobo2021 I cannot find where to change "tree: Directory structure of workspace". Can you point me to it?
- @runjinz please check how it looks with the new text. Notice some descriptions might be long. Show some screenshots if any problem.
> Refine context command descriptions

- src/handler/updateConfig.ts
- src/handler/userAccessKey.ts
- src/panel/statusBarView.ts
Update commands after devchat updated.
> Update commands after devchat update

- package.json
- src/views/pages/ChatPanel.tsx
- Changed the default AI model from 'gpt-4' to 'gpt-3.5-turbo' in package.json.
- Rearranged the model selection order in ChatPanel.tsx, moving 'gpt-4' to the end.
> Update default AI model and rearrange model selection

- package-lock.json
- src/views/components/BalanceTip/index.tsx
- src/views/components/WechatTip/index.tsx
- src/views/pages/ChatPanel.tsx
> feat: add wechat tip

- package.json
- src/context/contextSummary.ts
- src/context/loadContexts.ts
- src/contributes/commands.ts
- tools/askcode_summary_index.py
- Removed redundant commands related to ask-code-summary from package.json.
- Created a new file contextSummary.ts to handle the ask-code-summary context.
- Registered the ask-code-summary context in loadContexts.ts.
- Refactored the ask-code-summary related functions in commands.ts for better code organization and readability.
- Updated the askcode_summary_index.py script to handle target directory for indexing.
> Refactor ask-code-summary feature and remove redundant commands

- src/views/pages/ChatPanel.tsx
- Removed the GPT-4 chip from its original position.
- Added the GPT-4 chip after the GPT-3.5-16K chip.
> Reorder chat panel chips

- src/views/components/InputMessage/index.tsx
- Adjusted the width of the Stack component within the InputMessage component to "calc(100% - 60px)" to ensure proper spacing.
> Update InputMessage component width

- src/views/stores/ChatStore.ts
- Changed the rechargeSite URL from 'https://test.devchat.ai/pricing/' to 'https://devchat.ai/pricing/' in ChatStore.ts.
> Update rechargeSite URL in ChatStore

- src/util/python_installer/app_install.ts
fix devchat install error. while mamba fails, use conda replace.
> while mamba fails, use conda replace.

- src/toolwrapper/devchat.ts
- Introduced a new variable 'llmModel' to fetch the OpenAI model configuration from 'DevChat'.
- If 'llmModel' is present, it is added to the arguments list.
> Added support for configurable OpenAI model in DevChat

- .vscode/settings.json
- package-lock.json
- package.json
- src/context/contextRefDefs.ts
- src/contributes/commands.ts
- src/contributes/commandsBase.ts
- src/extension.ts
- src/handler/historyMessagesBase.ts
- src/handler/loadHandlers.ts
- src/handler/regCommandList.ts
- src/handler/regValidModelList.ts
- src/handler/sendMessage.ts
- src/handler/userAccessKey.ts
- src/panel/statusBarView.ts
- src/toolwrapper/devchat.ts
- src/util/apiKey.ts
- src/util/commonUtil.ts
- src/views/components/CurrentMessage/index.tsx
- src/views/components/Header/index.tsx
- src/views/components/InputMessage/index.tsx
- src/views/components/MessageList/index.tsx
- src/views/pages/ChatPanel.tsx
- src/views/stores/ChatStore.ts
- src/views/stores/InputStore.ts
- test/handler/sendMessageBase.test.ts
- test/util/apiKey.test.ts
> Improve input ux

- src/views/components/BalanceTip/index.tsx
- Set text color of balance tip modal to match VS Code theme
> Improve balance tip styling

- src/contributes/commands.ts
- src/handler/regValidModelList.ts
- src/panel/statusBarView.ts
> update key setting flow

- src/contributes/commands.ts
don't clear api key when escape
> don't clear api key when escape

- src/contributes/commands.ts
- src/panel/statusBarView.ts
- src/panel/statusBarViewBase.ts
- src/panel/webviewManager.ts
> Update new topic

- .gitignore
- package.json
- src/extension.ts
- src/util/apiKey.ts
- src/views/components/MessageMarkdown/index.tsx
Support code llama and llama-2-70B model.
> Code llama support

- src/contributes/commands.ts
- src/handler/sendMessage.ts
- src/util/python_installer/install_askcode.ts
> update devchat-ask version

- src/contributes/commands.ts
- src/handler/checkDevChatAsk.ts
- src/util/python_installer/install_askcode.ts
install devchat-ask package by webview. it will check devchat-ask is ready before /ask-code execute.
> update devchat-ask version to 0.1.3

- src/panel/statusBarViewBase.ts
Reset default model when current default model is invalid but valid models exist.
> update default llm model

- src/contributes/commands.ts
- src/extension.ts
- src/panel/statusBarView.ts
- src/toolwrapper/devchat.ts
- src/util/apiKey.ts
> fix invalid key error

- .circleci/config.yml
- .gitignore
- test/workflows/commit_cases.py
- test/workflows/ui_parser.py
- test/workflows/workflow_test.py
Run workflow test before publish a release.
Workflow test need OPENAI_API_KEY and OPENAI_API_BASE in environment.
> Add workflow tests

- src/toolwrapper/devchat.ts
- src/util/commonUtil.ts
Update commonUtil.ts and devchat.ts to include OPENAI_BASE_URL environment variable.
> Add OPENAI_BASE_URL environment variable

- test/workflows/ui_parser.py
- Updated UI block pattern in ui_parser.py to match different formats
> chore: Update UI block pattern in ui_parser.py

- package.json
- prompt_test.py
- src/contributes/commandsBase.ts
- src/panel/statusBarViewBase.ts
- test/contributes/commandsBase.test.ts
This pull request updates the `package.json` file to enhance readability and maintenance.
- Reordering properties for consistency.
- Adding new properties along with their descriptions.
- Removing any properties that are no longer used.
These changes aim to improve the clarity and management of the project configuration.
> Refactor: Reorganize and update package.json properties

- src/panel/codeLens.ts
This pull request enhances the unit testing configuration by adding setup for the `codeLens.ts` file.
- New unit test configuration specific to `codeLens.ts` has been added.
- Included `objectName` and `promptGenerator` in the test configuration for improved testing clarity.
- The updated unit test configuration has now been embedded into the branch.
> Update Unit Test Configuration for codeLens.ts

- src/handler/fileHandler.ts
- src/handler/handlerRegister.ts
This pull request introduces a new utility `fileHandler` to streamline file read and write operations.
- The addition of `fileHandler.ts`, encapsulating the read and write functionality.
- Registration of `readFile` and `writeFile` handlers within `handlerRegister.ts`.
- Necessary imports of the `readFile` and `writeFile` functions in `handlerRegister.ts`.
No issue needs to be closed as there was no issue id provided.
> Feature: Introduce fileHandler for Read and Write Operations

- src/handler/sendMessage.ts
Fix context error. Only last context file is add as context file.
> Fix contextInfo handling in sendMessage.ts

- test/workflows/commit_cases.py
While content is None, there will an error.
> Fix content concatenation in commit_cases.py

- package.json
- src/extension.ts
- src/util/apiKey.ts
- src/util/commonUtil.ts
This pull request addresses the enhancements outlined in issue [#235](https://github.com/devchat-ai/devchat/issues/235), which involves updating the devchat-api to support the latest Large Language Models (LLM) including Google's newest offerings. The updates have been made to ensure that our API remains competitive and continues to perform at high standards with the latest technological advancements in LLMs.
**Changes:**
- Deprecated 1106 and 16k GPT-3.5 model configurations have been removed.
- GPT-3.5 configuration has been updated to the latest stable version.
- Other models such as Claude, Xinghuo, GLM, and ERNIEbot have also been updated to their latest versions.
- The default model has been changed to Claude 2.1.
- New model integrations have been validated and tested to ensure …
> Integrate Latest Large Language Models into devchat-api

- src/util/commonUtil.ts
This pull request introduces several updates and enhancements to the devchat API and related features:
- Updated the `saveModelSettings` to use the new default model settings.
> Fix default model not exist error

- src/extension.ts
This PR introduces additional comments to parts of the codebase to enhance overall readability and maintainability as requested in issue devchat-ai/devchat#275.
Specifically, detailed comments were added to the `isProviderHasSetted` function, including descriptions and expected return types, to assist current and future project contributors.
Closes devchat-ai/devchat#275.
> Improve Code Documentation for Better Readability

- src/contributes/codecomplete/ast/ast.ts
- src/contributes/codecomplete/ast/findFunctions.ts
- src/contributes/codecomplete/promptCreator.ts
This pull request introduces optimizations to code completion performance by integrating distributed computing and improving the caching system. We've implemented the following enhancements:
- A refined AST caching mechanism ties cache entries to filepaths and their associated content hashes for effective validation.
- Optimized function lookups are now cached according to file extension, significantly reducing the number of redundant computational operations.
- Caching of symbol definitions has been added to decrease the frequency of AST parsing and query executions, expediting the code completion process.
These improvements aim at addressing the issues raised in [#320](https://github.com/devchat-ai/devchat/issues/320) and should result in a more efficient and speedy code completion …
> Enhance Code Completion Performance with Distributed Caching Mechanisms

- src/contributes/codecomplete/codecomplete.ts
This pull request addresses an issue where the code completion hint range was set incorrectly, causing relevant completion suggestions not to appear as expected. Changes include an added function to verify substring subsequences and an improvement in the logic for determining the appropriate hint range. These modifications ensure that completion suggestions are displayed correctly, even in edge cases.
Closes devchat-ai/devchat#322.
> Fix: Optimize code completion hint range for better UX

- src/panel/codeLens.ts
This pull request includes changes to enforce a check for the existence of the IDE configuration file before proceeding with the initialization process.
- A missing IDE configuration file check has been added to prevent potential initialization errors.
> feat: Ensure IDE Configuration File Existence Before Initialization

- src/contributes/codecomplete/ast/findFunctions.ts
- src/contributes/codecomplete/ast/findIdentifiers.ts
- src/contributes/codecomplete/ast/language.ts
- src/contributes/codecomplete/ast/treeSitter.ts
- src/contributes/codecomplete/astIndex/createIdentifierSet.ts
- src/contributes/codecomplete/astIndex/index.ts
- src/contributes/codecomplete/astIndex/indexStore.ts
- src/contributes/codecomplete/astIndex/types.ts
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
- src/contributes/codecomplete/symbolindex/embedding.ts
- src/contributes/codecomplete/symbolindex/index.ts
- src/extension.ts
- webpack.config.js
This pull request introduces improvements to our code completion features, focusing on the identification of similar code contexts to provide more relevant recommendations. Changes include the implementation of a mechanism for analyzing the current code context and matching it with existing similar code fragments and the optimization of the code completion hint range detection process. Additionally, updates to subproject references ensure seamless integration of new tools.
With these changes, developers should experience more accurate and efficient code completion suggestions, making coding tasks more streamlined and less time-consuming.
The following commits are included in this pull request:
- a2ead073ab6f66396689ceadddac4dd6fcf5ad0e: Optimize code completion hint range detection
- …
> Enhance Code Completion with Context Similarity Analysis

- src/contributes/codecomplete/astIndex/index.ts
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/gitDiffWatcher.ts
- src/contributes/codecomplete/promptCreator.ts
This pull request introduces a new feature that enhances the code completion mechanism by factoring in recently edited files, thereby making suggestions more context-aware and relevant to the developer's recent work.
1. Implemented `GitDiffWatcher` to track file changes, which serves as a cornerstone for the new feature by providing valuable context.
2. Adjusted the prompt creation process to incorporate recent edits and git diff context, ensuring highly relevant code completion suggestions.
3. Refactored the code completion system for improved performance:
- Removed performance logging and unused timing variables to streamline the code.
- Optimized the search logic for a smoother operational experience.
These modifications align with the rationale and expected behaviors requested in …
> Integrate Recent Files into Code Completion for Smarter Suggestions

- src/contributes/codecomplete/ast/collapseBlock.ts
- src/contributes/codecomplete/ast/findIdentifiers.ts
- src/contributes/codecomplete/astTest.ts
- src/contributes/codecomplete/chunkFilter.ts
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/gitDiffWatcher.ts
- src/contributes/codecomplete/promptCreator.ts
This pull request introduces two main changes:
1. **Performance Enhancement**: Resolves performance bottlenecks for code completion, ensuring a smoother experience when using this feature.
2. **Debug Config Update**: Simplifies the debug configuration by removing the `COMPLETE_DEBUG` environment variable and introducing a new config variable. This update also ensures the AST output is logged consistently, aiding in debugging processes without additional checks.
The changes made here are intended to improve code quality and developer experience by streamlining configurations and enhancing performance where it's most noticeable.
> Improve Code Completion Performance and Streamline Debug Configs

- package-lock.json
- src/handler/codeBlockHandler.ts
- src/handler/handlerRegister.ts
- src/handler/messageHandler.ts
- test/handler/codeBlockHandler.test.ts
- test/mocks/vscode.js
This pull request introduces enhancements to the file creation process within the `codeBlockHandler` and adds a suite of unit tests to ensure the robustness of its functionality.
- Refactored and streamlined the `createAndOpenFile` function, improving document creation and opening.
- Added detailed JSDoc comments to the `createAndOpenFile` function for better maintainability and developer understanding.
- Implemented unit tests covering various content cases and edge scenarios, such as unsupported languages and missing content.
- Integrated mocks for vscode API to accurately simulate the file creation and opening processes.
- Updated the `devchat` version to 0.1.74 to maintain dependency consistency.
These improvements aim to enhance the development experience by providing more intuitive …
> Enhanced file creation and added tests for codeBlockHandler

- src/contributes/codecomplete/codecomplete.ts
This PR addresses the issue reported in [Issue 332](https://github.com/devchat-ai/devchat/issues/332) where the code completion would trigger again despite partial acceptance of suggestions. With the following enhancements, the issue should now be resolved:
- Reuse previous code completion results if the new input prefix matches, minimizing redundant computations.
- Maintain tracking of the past code completion details to avoid unnecessary re-triggering of the code completion mechanism.
- Modify the logic that determines whether to present new suggestions or to reuse existing ones, optimizing the tool's performance and the coding experience.
By implementing these changes, the system will now avoid initiating a new code completion process when the user continues to type in accordance with …
> Optimize code completion to prevent duplicates

- src/contributes/codecomplete/codecomplete.ts
This pull request addresses the issue where the symbol selection widget was not providing code completion suggestions to users. By commenting out the problematic check, code suggestions are now appropriately triggered during symbol selection, enhancing user experience and workflow.
Specific changes made include:
- Ensuring code suggestions are presented during symbol selection.
- Optimizing the inline completion behavior for a smoother development process.
With these adjustments, the expected behavior described in issue [#333](https://github.com/devchat-ai/devchat/issues/333) is now met. Users should receive relevant code completion suggestions when they engage the symbol selection widget.
Closes devchat-ai/devchat#333
> Fix code completion for symbol selection widget

- src/toolwrapper/devchat.ts
This pull request introduces the capability to select a specific model to be used during unit tests. This will ensure consistency between tests and production environments.
- An environment variable has been added to configure the model used during unit testing.
- This change enhances the reliability of our test suite by utilizing actual configured model data.
This update is crucial for maintaining the integrity and stability of our testing strategy.
> Enable Use of Specific Models in Unit Tests for Consistency

- package.json
- src/contributes/codecomplete/ast/collapseBlock.ts
- src/contributes/commands.ts
- src/contributes/quickFixProvider.ts
- src/extension.ts
This pull request introduces the AI-Powered Quick Fix feature as requested in issue #345. The feature aims to enhance the developer experience in VSCode by enabling automatic suggestions for code fixes, which are generated via AI analysis of the detected coding errors.
Key Highlights:
- A new Quick Fix command has been added as per the feature request specification.
- Added `collapseFileExcludeSelectRange` function to facilitate precise code analysis.
- Quick Fix provider is now registered and ready to provide AI-powered suggestions to the users.
The integration of this feature is expected to significantly reduce the time spent on error diagnosis and correction, providing both educational and productivity benefits to developers.
As the feature has been implemented, this pull request …
> Implement AI-Powered Quick Fix for VSCode Plugin

- src/contributes/commands.ts
This PR introduces bilingual support for the Quick Fix feature within our devchat VSCode Plugin, providing both English and Chinese language prompts to improve usability for a broader user base.
Key Changes:
- A refactoring of the delay in Quick Fix activation to a more structured and maintainable function.
- An implementation of language-specific prompt generation to provide bilingual Quick Fix guidance.
- The addition of Chinese language support, enriching our feature set and aligning with user needs.
These enhancements aim to address the accessibility concerns discussed in [devchat-ai/devchat#351](https://github.com/devchat-ai/devchat/issues/351) and align with our commitment to creating an inclusive tool for all users, regardless of their primary language.
The team has put significant …
> Add Bilingual Support for Quick Fix Prompts in VSCode Plugin

- src/contributes/codecomplete/chunkFilter.ts
- src/contributes/codecomplete/codecomplete.ts
This pull request introduces updates to the code completion feature, aiming to improve its relevance by filtering out certain patterns that may cause distractions during development. As described in issue #353, the adjustments made are designed to exclude patterns that denote inapplicable code completion suggestions such as filenames in comments and placeholders for omitted code.
Enhancements:
- Code completions will no longer suggest completions for comments followed by a filename (e.g., '//<filename>').
- Code completions that include 'Code omitted...' are now correctly filtered out to prevent irrelevant suggestions.
- The prefix gathering logic for inline completions now better considers the context provided by previous lines.
These improvements are expected to streamline the …
> Implement enhanced filtering for code completion to optimize performance

- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
This PR introduces the integration of the DevChat API to the VSCode extension, enabling access to large model code completions that enhance coding efficiency and provide more accurate, context-aware suggestions.
- Adding support for DevChat API as a new source for code completion.
- Implementing dynamic model selection based on the user's coding context.
- Introducing robust error handling and logging for API requests to ensure reliability and security.
This effectively addresses the feature request outlined in issue [#358](https://github.com/devchat-ai/devchat/issues/358), closing it upon this PR's merge.
Closes devchat-ai/devchat#358
> Feat: Introduce DevChat API Integration for Enhanced Code Completion

- src/contributes/codecomplete/codecomplete.ts
This pull request addresses the screen flickering issue described in [#362](https://github.com/devchat-ai/devchat/issues/362). A refactoring of the autocomplete logic, including the addition of a preCompletionItem and enhanced handling of autocompletion items, has been implemented to eliminate the flickering.
- A temporary storage for the current autocomplete item has been introduced to retain its state before displaying.
- The logic for returning autocomplete items has been updated to provide a smoother experience without causing screen flickers.
- Code combining the current line prefix and response code has been improved for efficiency.
These changes should resolve the flickering issue experienced when code is autocompleted character by character.
Closes devchat-ai/devchat#362
> Fix Screen Flickering Issue During Code Autocompletion

- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
This pull request introduces enhancements to the code completion logs by including specific source information in the context. The update follows the proposal from issue [#369](https://github.com/devchat-ai/devchat/issues/369) and is intended to improve the relevance and accuracy of code completions.
**Changes introduced**:
- The language model within the code completion feature is now updated to `starcoder2:15b` for elevated performance.
- The process for creating prompts has been overhauled to include various elements such as 'recent edit documents', 'task', 'call function define', 'similar blocks', and 'symbol defines', providing better context recognition in completion logs.
- A fallback mechanism to 'nvidia/starcoder2:15b' has been established to ensure greater reliability when no …
> Enhance Code Completion Context Clarity with Specific Source Information

- src/toolwrapper/devchat.ts
This PR updates the DevChat configuration files and the commit hash for the GUI submodule.
> Update DevChat configuration and GUI submodule

- package.json
- src/contributes/commands.ts
- src/extension.ts
- src/handler/workflowCommandHandler.ts
- src/init/chatConfig.ts
- src/panel/devchatView.ts
- src/panel/statusBarView.ts
- src/toolwrapper/devchat.ts
- src/util/python_installer/install_devchat.ts
checklist:
1. [ ] Add `MAMBA_BIN_PATH` in env var for the devchat (workflow engine) process
2. [ ] Add `WORKFLOW_BASE_PATH` into PYTHONPATH for the win32 embed python
3. [ ] Invoke `devchat workflow update` command when necessary (e.g. when activate the devchat plugin )
4. [ ] Update the `tools` submodule
5. [ ] Add the new workflow hosting submodule (remove the old one)
> [dev] Support workflow engine 2.0

- src/context/contextCustomCommand.ts
- src/contributes/codecomplete/ast/treeSitter.ts
- src/contributes/codecomplete/astIndex/index.ts
- src/contributes/codecomplete/astTest.ts
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
- src/contributes/codecomplete/symbolindex/embedding.ts
- src/extension.ts
- src/handler/messageHandler.ts
- src/handler/sendMessageBase.ts
- src/ide_services/services.ts
- src/panel/codeLens.ts
- src/toolwrapper/devchat.ts
- src/util/commonUtil.ts
- src/util/logger.ts
- src/util/logger_vscode.ts
- src/util/python_installer/conda_url.ts
This PR updates the `logger.trace` calls to enhance the readability of the codebase. No associated issue to be closed.
> Improve code readability by updating logger.trace calls

- src/contributes/codecomplete/codecomplete.ts
This PR introduces optimizations to the InlineCompletionProvider, ensuring a smoother code completion experience.
> Chore: Optimize InlineCompletionProvider for Better Performance

- src/contributes/codecomplete/chunkFilter.ts
This PR refactors the LLMStreamComplete class to improve code readability and maintainability.
> Refactor LLMStreamComplete class to improve code readability and maintainability

- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
This pull request includes two commits that refactor the LLM code. The first commit (a05e6caee1676348bcb0abddb5deeccd6a664058) refactors the code to use llmApiBase for the completion endpoint, enhancing the integration and functionality of the endpoint. The second commit (4eea931db1563c4968d9fb1b85346cbcdf008371) focuses on performance optimization and logging improvements for the LLM code, ensuring better performance and more detailed logging for debugging and monitoring purposes.
> Refactor LLM Code for Completion Endpoint and Performance Optimization

- src/contributes/codecomplete/chunkFilter.ts
- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/llm/countTokens.ts
- src/contributes/codecomplete/promptCreator.ts
- src/util/config.ts
This pull request includes several refactorings aimed at improving performance and fixing bugs. The changes include:
- Refactor DevChatConfig.get() method to support default values
- Refactor countTokens function to simplify and improve performance
- Refactor code to use "//" as a stop condition for devchatComplete
- Refactor LLMStreamComplete to handle empty lines in removeRepeatBlock
- Refactor submodule commit references in gui
> Refactor code for performance optimization and bug fixes

- src/contributes/commands.ts
This pull request refactors `commands.ts` to include a `MessageHandler` for sending a `codeDiffApply` command.
> Refactor commands.ts to include MessageHandler for sending a codeDiffApply command

- src/contributes/codecomplete/codecomplete.ts
This PR includes two commits:
- Refactor subproject commit in gui
- feat: Add IDE and language information to log event requests in InlineCompletionProvider
> Refactor subproject commit in gui and add IDE and language information to log event requests

- src/handler/configHandler.ts
- src/handler/handlerRegister.ts
Refactor configHandler.ts to read and write YAML configuration files
> Refactor configHandler.ts to read and write YAML configuration files

- src/contributes/codecomplete/codecomplete.ts
feat: Add model to completion event
- Added model property to LogEventRequest interface
- Included model in log events sent to server
- Retrieved model from DevChatConfig instance
> feat: Add model to completion event

- src/ide_services/services.ts
This PR refactors subproject commit in gui and getCurrentFileInfo endpoint, and adds CORS headers.
> Refactor subproject commit in gui and getCurrentFileInfo endpoint

- src/extension.ts
This PR addresses the issue where the default model was being incorrectly set. Changes include:
- Removed the code that sets the default model in the configuration
- Simplified the configuration migration process by removing unnecessary steps
> fix: Remove default model configuration

- src/contributes/commands.ts
This pull request includes two commits that refactor the subproject commit in the GUI and fix issues related to async operations and error handling. Specifically, the `registerQuickFixCommand` and `generatePrompt` functions have been updated to be async, improving their functionality and handling of active editor context. Error handling and context management in prompt generation have also been improved.
> Refactor and Fix: Async Updates and Error Handling

- src/contributes/codecomplete/promptCreator.ts
This PR fixes the issue where code completion exceeds context limit when function is folded in long files. Adjusted collapseCodeBlock function to respect complete_context_limit, implemented prefix and suffix length limiting to prevent exceeding limit, and ensured code completion does not exceed context limit even with folded functions. Closes devchat-ai/devchat#403
> Fix: Limit code completion context to prevent exceeding limit

- src/handler/diffHandler.ts
- src/ide_services/endpoints/unofficial.ts
- src/ide_services/services.ts
This pull request introduces several new features and improvements:
- Implement code editing functionality with applyDiffToCode function
- Add getCodeEditorPath to locate platform-specific binaries
- Integrate new functionality with existing diff display system
- Handle OPTIONS requests for CORS support in RPC server
- Introduce autoedit flag for automatic code editing
- Update diffApply function to include "autoedit" parameter
- Update tools
These changes enhance the application's capabilities in code editing, improve cross-origin resource sharing, and provide more flexibility in applying diffs to code.
> feat: Add code editing, diff display, and CORS support

- src/ide_services/endpoints/unofficial.ts
- src/ide_services/services.ts
This PR implements the select range functionality:
- Implement selectRange function in UnofficialEndpoints
- Add select_range endpoint to functionRegistry
- Import vscode module for text editor operations
This enhancement allows users to select a specific range of text in the editor.
> feat: Add select range functionality

- package.json
- src/contributes/commands.ts
- src/contributes/quickFixProvider.ts
This pull request introduces a new quick fix option using DevChat and renames the existing quick fix command.
- Added "Fix using DevChat" as a preferred quick fix action
- Renamed existing quick fix command to "Ask DevChat"
- Updated package.json and TypeScript files to reflect new commands
This enhancement provides users with more options for resolving issues quickly and efficiently using DevChat.
> feat: Add new quick fix option using DevChat

- src/contributes/codecomplete/llm.ts
- Refactor stream processing for better chunk handling
- Add max_tokens parameter to API payload
- Implement simulated stream receive for testing purposes
> fix: Improve LLM stream handling in devchatComplete function

- src/contributes/codecomplete/promptCreator.ts
This pull request adds logging to various parts of the code completion process to better handle and track errors.
- Added try-catch blocks to handle errors in creating task description context.
- Added logging for errors in creating call definition context, similar block context, symbol context, recent edit context, and neighbor file context.
- Wrapped the main function logic in a try-catch block to log errors in createPrompt.
No issue to close.
> feat: Add logging in code completion

- src/contributes/commands.ts
- Added missing directory path for Merico scripts
- Updated directory existence check to use the new path
- Ensured workflow commands are correctly installed
> fix: Correct workflow directory path

- src/util/python_installer/python_install.ts
This PR adds the ability to configure the conda-forge URL used for Python installation.
Changes:
- Implement getCondaForgeUrl function to fetch URL from config
- Use configurable URL in Python installation process
- Add error handling and fallback to default URL if needed
This enhancement provides more flexibility in the Python installation process by allowing users to specify a custom conda-forge URL.
> feat: Add configurable conda-forge URL for Python installation

- package-lock.json
- package.json
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/llm.ts
- src/contributes/commands.ts
- src/extension.ts
- src/ide_services/endpoints/updateSlashCommands.ts
- src/panel/statusBarView.ts
- yarn.lock
This PR includes the following changes:
- Update packages lock
- Update submodules
- Add command to trigger code completion by shortcut
- Replace fetch with node-fetch
- Update install commands logs
- Add log for update slash commands
- Add startup log
- Update keybindings
- Add Chinese menu
- Update commands
These changes improve the project's dependencies, add new features like code completion shortcuts and Chinese menu, and enhance logging for better debugging and user experience.
> Update packages, add features, and improve logging

- src/contributes/codecomplete/codecomplete.ts
- src/contributes/commands.ts
- src/handler/messageHandler.ts
This PR includes the following changes:
- Update submodules
- Refactor code completion event logging
- Add manual trigger flag to log events
- Implement message logging for code completion
- Update public workflow installation process
> chore: Update submodules and optimize code completion

- src/contributes/commands.ts
This PR implements auto-activation of the chat panel to enhance user experience and improve workflow efficiency for DevChat interactions.
Changes:
- Implement ensureChatPanel function call in command
- Automatically open plugin window when needed
- Streamline DevChat interaction process
This change aims to make the plugin more user-friendly by reducing manual steps required to start a conversation.
> feat: Add auto-activation of chat panel

- prebuild.js
- src/context/contextCodeSelected.ts
- src/context/contextFileSelected.ts
- src/contributes/commands.ts
This PR includes several improvements and refactoring changes:
- Optimized workflow update and command list process
- Improved file path handling in contextFileSelected and contextCodeSelected
- Added fallback for relative path calculation
- Handled cases where workspaceDir is undefined
- Ensured fileSelected is used as a fallback
- Added missing semicolons and improved code formatting in prebuild.js
- Updated submodules
These changes enhance the robustness and maintainability of the codebase.
> Refactor and improve file path handling

- src/handler/handlerRegister.ts
- src/handler/openlinkHandler.ts
- Add new openLink handler to manage external URL navigation
- Register openLink handler in message handler system
- Implement URL opening functionality using vscode.env.openExternal
- Update GUI submodule
> feat: Add external link handler and update GUI submodule
