- media/inputContainer.js
This pull request adds two new features to the project:
1. **Auto-resizing message input:** With this feature, the message input field will automatically resize based on the number of lines of text entered. Additionally, the input container will also resize accordingly. This has been implemented by introducing a new function called `autoResizeTextarea()`, which is called on input and sets the height of the message input and input container based on the number of lines of text entered. The default height is set to 16.
2. **Support for sending messages with Ctrl+Enter:** With this feature, users can now send messages by pressing Ctrl+Enter instead of having to press Enter and then remove the new line. If the user presses Enter without Ctrl or Shift, a new line is added to the input field. …
> Add auto-resizing functionality and Ctrl+Enter support to message input

- src/views/ChatPanel.tsx
- Added a messageCount constant to limit the number of displayed messages
- Removed excess messages when the message length exceeds double the messageCount
- Ensured only the last 5 messages are loaded from the history
> Limit displayed chat history to 5 messages

- src/toolwrapper/devchat.ts
- Check for stderr in the 'close' event
- Log the error to the logger channel
- Show the logger channel if an error occurs
> Add error logging to DevChat child process

- src/views/ChatPanel/index.tsx
Add a default command menu icon for patterns other than 'code' and 'commit_message' in the ChatPanel component.
> feat(chatpanel): add default command menu icon

- .circleci/config.yml
- README.md
- docs/publish.md
This commit introduces a CircleCI configuration that enables automatic building of the VSCode extension on every main branch update. It also sets up automatic publishing to the VSCode Marketplace whenever a new tag is created on the main branch. This workflow significantly improves the CI/CD process of the extension development.
> Add CircleCI Configuration For Automated Build And Publish

- src/views/ChatPanel/index.tsx
- Import IconRotateDot from @tabler/icons-react
- Add hasError state to track if an error occurred
- Update receiveMessage handler to set hasError state if message.isError is true
- Add regeneration button with IconRotateDot when hasError is true
- Add onClick handler for regeneration button to clear error and request regeneration
> Add error handling and regeneration button to ChatPanel

- src/extension.ts
- tools/install.py
- Add await keyword to secretStorage.store call in extension.ts.
- Set statusBarItem.command to undefined instead of an empty string.
- Force pipx installation in install.py by adding --force flag.
> Improve secretStorage usage and pipx installation

- src/handler/sendMessage.ts
- src/topic/topicManager.ts
- Store partial chat response data in a separate variable.
- Concatenate partial data with responseText when chatResponse.isError is true.
- Comment out setCurrentTopic call in topicManager.ts.
> Improve handling of partial chat responses and topic creation

- src/command/commandManager.ts
- src/command/customCommand.ts
- src/handler/regCommandList.ts
- Added args property to Command interface in commandManager.ts and customCommand.ts.
- Updated regCommandList handler to convert command patterns with args.
- Replaced {{prompt}} with an array of empty strings based on the args count.
> Add args property to Command interface and update regCommandList

- src/topic/topicManager.ts
- Imported logger from '../util/logger' in topicManager.ts.
- Added logger.channel()?.info() for "Topic not found" cases.
> Add logger to TopicManager for better error handling

- src/views/ChatPanel/InputMessage.tsx
In this commit, we simplified the icon rendering logic in the InputMessage component by removing the unnecessary condition for the <custom command> name. This change makes the code more concise and easier to understand.
> Refactor: Simplify icon rendering in InputMessage component

- src/views/ChatPanel/index.tsx
In this commit, we updated the ChatPanel component to display error messages using the Alert component from the Mantine library. This change improves the user experience by providing a clear and consistent way to display error messages in the chat interface. The error message is now stored as a string in the hasError state, and the Alert component is conditionally rendered based on the presence of an error message.
> Enhancement: Display error messages in ChatPanel using Alert component

- src/toolwrapper/devchat.ts
- Update devchat.ts to include a double dash in the chat() method.
- Ensure proper separation of options and content in the chat() method.
> Add double dash to DevChat arguments

- src/toolwrapper/devchat.ts
- src/util/uiUtil_vscode.ts
- Set PYTHONUTF8 to 1 in the DevChat class.
- Ensures proper handling of UTF-8 encoding.
> Add PYTHONUTF8 environment variable to DevChat

- src/handler/historyMessagesBase.ts
- Modify loadTopicHistoryLogs to accept topicId as a parameter.
- Update updateCurrentMessageHistory to accept topicId as a parameter.
- Pass topicId to loadTopicHistoryLogs and updateCurrentMessageHistory in historyMessagesBase.
- Add a check for topicId change before updating message history.
> Refactor historyMessagesBase to accept topicId as parameter

- src/views/InputMessage.tsx
- Modified the condition in InputMessage.tsx to check if the IME composition is in progress.
- This prevents the message from being sent when the Enter key is pressed during IME composition.
> Prevent sending message on Enter key press during IME composition

- src/views/CodeBlock.tsx
- src/views/MessageContainer.tsx
- Added messageType prop to CodeBlock component in CodeBlock.tsx.
- CodeBlock now renders differently for 'bot' and other message types.
- Updated MessageContainer.tsx to pass messageType to CodeBlock.
> Differentiate code block rendering based on message type

- src/views/CodeBlock.tsx
- Changed the tooltip label from 'Replace' to 'Replace File' in CodeBlock.tsx.
- This provides a clearer indication of the button's functionality.
> Update tooltip label in CodeBlock component

- src/action/actionManager.ts
- Moved the registration of actions inside the instance creation conditional block.
- This ensures that actions are only registered when the instance is first created.
> Refactor ActionManager class initialization

- src/topic/topicManager.ts
- Added a check to ensure the messageHash equals the firstMessageHash before updating.
- This prevents unnecessary updates and ensures the correct message is targeted for deletion.
> Update condition in deleteMessage method

- src/views/CurrentMessage.tsx
- Removed unused import 'selectResponsed' from chatSlice.
- Replaced 'selecHasDone' with 'selectResponsed' for better clarity.
- Removed unnecessary condition check for 'hasDone' in useEffect.
- Added 'responsed' as a dependency in useEffect to trigger update when response is received.
> Refactor CurrentMessage component in chat feature

- src/panel/statusBarViewBase.ts
- Removed unnecessary if-else condition for errorInstall.
- Moved devchatCommandEnv extraction outside the if-else block.
- Added condition to check if devchatCommandEnv exists before updating configuration and setting devchatStatus.
- Added else block to handle case when devchatCommandEnv is undefined.
> Refactor DevChat installation error handling

- tools/install.py
- Changed the type hinting for the 'pipcmd' parameter in 'pip_cmd_run' and 'pip_cmd_with_retries' functions.
- The 'pipcmd' parameter now accepts any type, not just list of strings.
> Update pip command functions in install.py

- src/contributes/commands.ts
- src/util/apiKey.ts
- test/util/apiKey.test.ts
- Modified the API key validation logic to check for non-empty strings before validating.
- Updated the API key prefix from 'sk.' to 'sk-' in the ApiKeyManager and corresponding tests.
- Adjusted the test cases to reflect the new API key format.
> Update API key validation and handling

- package.json
- src/contributes/commands.ts
- src/extension.ts
- src/handler/historyMessagesBase.ts
- src/panel/statusBarView.ts
- src/util/apiKey.ts
- test/handler/sendMessageBase.test.ts
- test/util/apiKey.test.ts
- Renamed and split the API key settings in package.json into DevChat and OpenAI specific keys.
- Updated the commands for setting API keys to handle OpenAI and DevChat keys separately.
- Modified the ApiKeyManager to handle and validate OpenAI and DevChat keys separately.
- Updated the status bar view to use the DevChat access key command.
- Adjusted the tests to reflect the new handling of API keys.
> Separate handling for OpenAI and DevChat API keys

- tools/install.py
- Modified the virtual environment creation command to specify Python version as 3.11.4.
- This change affects the print statement and the subprocess.run command in the virtualenv_create_venv function.
> Specify Python version in virtual environment creation

- package.json
- src/toolwrapper/devchat.ts
- Added a new configuration option "DevChat.EnableFunctionCalling" in package.json.
- This option allows users to enable or disable function calling for GPT.
- Updated devchat.ts to check this configuration before pushing function options.
> Add option to enable/disable function calling in DevChat

- src/panel/devchatView.ts
- Extracted the logic for reloading custom definitions into a separate method, `reloadCustomDefines`.
- This method is now called in `resolveWebviewView` and `reloadWebview` to ensure custom definitions are always up-to-date.
> Refactor devchatView.ts to reload custom definitions

- src/panel/statusBarViewBase.ts
- Added a new boolean flag 'hasLoadTopics' to track whether topics have been loaded.
- If the devchat package has been installed and the API access key is valid, the 'loadTopics()' method of the TopicManager class is called.
- This ensures that topics are only loaded once when the dependencies are satisfied.
> Add hasLoadTopics flag and loadTopics() call

- src/views/components/InputMessage/index.tsx
- Imported 'useTimeout' hook from '@mantine/hooks' in InputMessage/index.tsx.
- Added a setTimeout function in the handleSendMessage function in InputMessage/index.tsx to scroll to the bottom after clearing the input field.
> Clear input field and scroll to bottom after sending message

- src/context/contextRefDefs.ts
- Updated the response text trimming logic in getUndefinedSymbols function in contextRefDefs.ts.
- Now the function correctly extracts the JSON content from the response text.
> Refine response text parsing in getUndefinedSymbols

- src/views/components/InputMessage/index.tsx
- Wrapped the contextMenusNode and commandMenusNode with ScrollArea.Autosize for better UX.
- Set the maximum height of the ScrollArea to 240 and scroll type to 'always'.
- This change ensures that the menus are scrollable and do not exceed a certain height.
> Add ScrollArea to context and command menus in InputMessage component

- src/views/components/MessageMarkdown/index.tsx
- src/views/stores/ChatStore.ts
- Added a case for "#settings" in MessageMarkdown component to handle settings command.
- Included "#settings" in the list of custom anchors.
- Replaced the settings button in ChatStore with a link to settings.
> Add settings link to DevChat

- src/views/components/InputMessage/InputContexts.tsx
- Wrapped the content of the Accordion.Panel in a ScrollArea component.
- This change allows the content to be scrollable when it exceeds the panel's height.
> Add ScrollArea to InputContexts component

- src/views/components/InputMessage/index.tsx
- Imported IconChevronDown from "@tabler/icons-react".
- Added closeButtonProps to the Popover component with IconChevronDown as children.
> Update InputMessage component with new icon and closeButtonProps

- src/handler/loadHandlers.ts
- src/handler/userAccessKey.ts
- Imported getUserAccessKey in loadHandlers.ts and registered it as a message handler.
- Created a new file userAccessKey.ts to handle getting user access keys.
- The getUserAccessKey function retrieves the API key, determines its type (DevChat or OpenAI), and gets the endpoint.
- If no API key is found, a message is sent with empty values.
> Add getUserAccessKey handler and related functionality

- src/action/runVSCodeCommand.ts
- src/handler/sendMessage.ts
- src/util/commonUtil.ts
- workflows/auto_command/action/new_file/handler.py
- In runVSCodeCommand.ts, added a condition to convert the first argument to a Uri if the command is 'vscode.open'.
- In sendMessage.ts, added logic to prepend the previous command to the message text if the message starts with '/'.
- In commonUtil.ts, modified the spawnAsync function to replace arguments starting with '$' with their corresponding environment variable values.
- In handler.py, added code to create parent directories for a new file if they don't exist.
> Implement various enhancements and fixes across multiple files

- src/util/python_installer/conda_install.ts
- src/util/python_installer/python_install.ts
- src/util/python_installer/readme.md
- Updated the conda installation directory from .devchat to .chat in conda_install.ts.
- Updated the mamba installation directory from .devchat to .chat in python_install.ts.
- Updated the installation directory in the readme.md file.
> Change conda installation directory from .devchat to .chat

- src/views/components/InputMessage/index.tsx
- src/views/components/MessageBody/index.tsx
- src/views/components/MessageMarkdown/index.tsx
- src/views/pages/ChatPanel.tsx
- src/views/stores/ChatStore.ts
- Extract chat panel width state into Chat store
- Remove width prop drilling from parent components
- Use chat panel width via hook instead of props
- Pass className prop to MessageMarkdown for width styling
- Extend MessageMarkdown props to allow className
- Update MessageBody to get width styles
> Update components to use chat panel width from store

- src/views/stores/ChatStore.ts
- Removed the self.messages.pop() call in the process of sending a 'regeneration' command.
> Remove line popping items from messages array in ChatStore

- src/views/components/ChatMark/index.tsx
- Removed conditions related to 'disabled' state when creating checkbox and editor widgets in the ChatMark component.
- Widgets will now always preserve their original state as defined in the markdown.
> Fix state management in ChatMark component

- src/contributes/commands.ts
- src/handler/workflowCommandHandler.ts
This PR addresses a bug (#156) where the command list was not displayed in the VS Extension. Changes have been made to correct the async/await usage in command handling, leading to improved performance and reliability.
The following updates are included:
- Improved the async/await usage in command handling.
- Refactored `updateSysCommand` and `sendCommandListByDevChatRun` functions for better clarity and performance.
- Enhanced error handling during `updateSysCommand` execution.
With these updates, users should now be able to see the commands listed as expected when using the extension.
Fixes #156
> Fix: Command list not displaying due to async/await issues

- src/contributes/commands.ts
- src/panel/statusBarView.ts
- src/util/progressBar.ts
This pull request addresses the issue reported in [#155](https://github.com/devchat-ai/devchat/issues/155), where users were experiencing an excessive number of notifications every time they opened VS Code or a project.
Changes introduced:
- The informational messages for command readiness are no longer displayed during every startup.
- A new periodic check has been implemented to monitor the status of DevChat commands.
- The DevChat status bar item tooltip will now conditionally display based on specific events rather than always showing.
These changes aim to improve user experience by only showing notifications that are relevant to users' activities, conforming to the request of only showing them upon installation, updating, or when issues occur.
Closes devchat-ai/devchat#155.
> Reduce frequency of DevChat notifications on startup

- src/handler/codeBlockHandler.ts
This pull request addresses the issue when code is inserted without clear visual feedback on its location. Changes have been implemented to ensure that when a new code block is inserted, the editor view jumps to center the code block in the viewport, and the newly inserted text is highlighted for better visibility.
- The `applyCode` function has been refactored to include checks for visibility and to ensure that the code block is positioned within the visible area of the editor.
- Additional logic has been added to calculate the text range position and check whether it is in the viewport. If not, the editor is adjusted to bring the newly inserted text into focus.
Through these enhancements, we aim to provide a more intuitive and user-friendly experience when working with code insertions …
> Fix: Center Editor to Newly Inserted Code Block

- src/toolwrapper/devchat.ts
This pull request addresses the issue where `devchat-core` was incorrectly outputting errors to the error stream during successful execution. 
The changes introduced include: 
- Adding conditional checks to ensure that any output to stderr during a successful execution is logged as a warning rather than treated as an error. 
- Refactoring the error handling process to align with the expected behavior of `devchat-core`. 
This should provide a more reliable and consistent execution status indication. 
Closes devchat-ai/devchat#200.
> Fix Inconsistent Error Handling in devchat-core

- src/contributes/commands.ts
- src/extension.ts
This pull request addresses two significant issues experienced by users:
- The sidebar not activating when clicking 'Add Tests', requiring a double-click to initiate the process
- An error message displaying 'Actual command not found, wanted to execute DevChat.Chat /25' when attempting certain operations
The updates include a delay to ensure the sidebar is properly activated on the first click and a reordering of the CodeLens provider registration to resolve command execution errors.
These fixes should enhance user experience with more responsive interactions and reduce the occurrence of confusing error messages.
Resolves devchat-ai/devchat#182
> Fix Sidebar Activation and DevChat Command Execution Issues

- src/context/contextRefDefs.ts
- src/ide_services/services.ts
This pull request introduces a new function `get_symbol_defines_in_selected_code` as part of the `add_tests` workflow. This function is designed to enhance the workflow by allowing better symbol definition handling within selected code segments. This is particularly useful for improving test coverage and accuracy.
No related issue was referenced for this change.
> Implement get_symbol_defines_in_selected_code Functionality

- src/ide_services/lsp/lsp.ts
This pull request addresses the bug reported in issue #233 where the `document_symbols` interface in `ide_services` was not returning the expected substructure information.
The interface now correctly processes the `DocumentSymbol` substructure by referencing `symbol.children` instead of using an instance type check. The changes ensure that the complete information is returned by the `document_symbols` interface.
Fixes: devchat-ai/devchat#233
> Fix document_symbols substructure information in ide_services

- src/handler/workflowCommandHandler.ts
- src/toolwrapper/devchat.ts
This pull request introduces the implementation for command recommendations with directory awareness on the welcome page, fulfilling the requirements of our feature request. With these changes, the welcome page will now recommend commands from the 'org' and 'sys' directories. Additionally, if a command lacks a sufficient description, the system will attempt to display the contents of the command's directory's README.md file. An error message will be shown if no README.md is available or if there is any other issue with the command input.
Changes Made:
- Added a 'path' property to the command struct for directory context.
- Updated command object creation to include the 'path' property when listing commands in the devchat run listing.
- Modified the CommandEntry interface in devchat tool …
> Feature: Command Recommendations with Directory Awareness on Welcome Page

- package.json
- src/extension.ts
- src/util/apiKey.ts
- src/util/commonUtil.ts
This pull request addresses the feature enhancement requested in issue [#239](https://github.com/devchat-ai/devchat/issues/239) by adding support for new language learning models in the VSCode plugin. Users can now easily switch between the codellama 70B, Mixtral-8x7B, and minimax models from within the editor, enhancing their development experience by leveraging different AI capabilities.
- Added configuration settings support for Model.CodeLlama-70B.
- Implemented support for Model.Mixtral-8x7B and Model.Minimax-abab6.
- Modified both the UI and API integration to enable new model selections within the plugin.
Resolves devchat-ai/devchat#239.
> Add Selection Support for codellama 70B, Mixtral-8x7B, and minimax Models in VSCode Plugin

- package.json
- src/contributes/commands.ts
- src/contributes/views.ts
- src/extension.ts
- src/handler/handlerRegister.ts
- src/handler/historyMessagesBase.ts
- src/handler/historyMessagesHandler.ts
- src/handler/sendMessageBase.ts
- src/handler/topicHandler.ts
- src/panel/devchatView.ts
- test/handler/sendMessageBase.test.ts
This PR streamlines the UI experience for VSCode Topics on smaller screens. With the changes, the VSCode Topic list no longer consumes half the screen space, as it is now internally managed similarly to the JetBrains plugin.
- A new topicHandler to better manage getTopics and deleteTopic functions.
- Refactoring of historyMessagesHandler to work with topicId.
- Elimination of redundant UI elements for topics and consolidation of views for a more streamlined interface.
- Update of subproject commitment hash as part of the enhancement process.
These improvements align the small screen experience with user expectations and follow the suggestions provided in issue [#225](https://github.com/devchat-ai/devchat/issues/225).
Filtering deleted topics and using TopicEntry as the …
> Refactor UI for Unified Topic Interaction on Small Screens

- src/topic/topicManager.ts
This pull request addresses the issue described in #240, where the deletion logic for topics within the VSCode plugin was not executing as intended. The fix includes a simplification of the deletion logic and ensuring that topic IDs are correctly recorded and removed from the application state.
- Simplification of deletion logic within `topicManager`
- Accurate recording of topic IDs in `.deletedTopics`
- Assurance of proper topic removal from application state
With these changes, users should now experience the correct deletion behavior when removing topics within the plugin.
Closes devchat-ai/devchat#240
> Fix: Resolve Topic Deletion Issue in VSCode Plugin

- package.json
- src/topic/topicManager.ts
- src/util/apiKey.ts
- src/util/commonUtil.ts
This PR addresses the issue where GPT-4 exceeded the max_tokens limit despite explicit configuration settings. Changes made ensure that token limits are enforced as per user requirements, providing two separate configuration parameters for input and output token limits.
The following fixes have been made:
- A `max_input_tokens` property has been introduced to configuration settings to explicitly define the maximum number of tokens for model input.
- Default values for `max_tokens` have been adjusted to ensure that the output does not exceed the set limit.
- For consistency, the identifier `gpt-4-1106-preview` has been renamed to `gpt-4-turbo-preview`.
With these changes, users should have reliable control over the length of generated content and better clarity on token limitation …
> Fix for GPT-4 Exceeding max_tokens Limit Configuration

- package.json
This pull request includes changes that remove the `api_secret` attribute from the model configuration within `package.json`. The update ensures best practices for API secret management by advocating the use of environment variables or a secrets manager, rather than hardcoding secrets within configuration files.
Changes:
- Removed `api_secret` from `package.json`.
- Ensured there are no defaults or descriptions left for `api_secret`.
The implementation aligns with modern security standards and minimizes potential risks associated with code-based secret management.
> feat: Remove api_secret attribute from model config

- src/extension.ts
This PR addresses the execution failures that occur when the input length to a model exceeds its default limits in VSCode, as noted in issue #248. To resolve this, we've added a functionality that allows users to set default model parameters, specifically maximum input token limits, thus enhancing user experience and preserving the model’s operation integrity.
The implementation ensures that the input length is checked prior to model execution. If it surpasses the set limits, the user is immediately notified, preventing execution errors associated with input length overflow.
Key features added:
- Model-specific max_input_tokens configuration to prevent overflow errors.
- Default token limits settings for each model configuration.
- Integration of default parameter setup within the …
> Implement Default Model Parameters in VSCode Settings

- package.json
- src/contributes/commands.ts
- src/handler/focusHandler.ts
This pull request introduces a keyboard shortcut for opening the DevChat view and focusing on the input field, addressing the feature request outlined in [#250](https://github.com/devchat-ai/devchat/issues/250).
- The addition of keybindings to trigger the DevChat view and automatically move the input focus to the chat input box.
- Implementation of a focusHandler function to manage the input focus upon using the shortcut.
This feature will improve efficiency by allowing users to start discussions quickly without the need to switch from keyboard to mouse. Additionally, it will enhance the usability of DevChat for those who prioritize keyboard navigation.
Closes devchat-ai/devchat#250
> Add Keyboard Shortcut for Focusing on DevChat Input

- src/ide_services/services.ts
This PR introduces a new endpoint `/ide_name` which is responsible for returning the name of the IDE currently in use. For now, it is hardcoded to return `vscode`.
- Addition of a new `/ide_name` endpoint in the service layer
- Implementation of a handler that returns `vscode` as the IDE name
- Reorganization of the endpoint definition for `/diff_apply` within the functionRegistry to maintain clean code structure.
No associated issue to close.
> feat: Implement /ide_name endpoint to retrieve IDE name

- src/util/diffFilePairs.ts
This PR introduces a fix for the case sensitivity problem on Windows platforms when applying patches using the diff view feature. The changes ensure that file paths are normalized to lowercase before pairing and looking them up, which addresses the mismatches caused by different casing in drive letters.
The following changes have been made:
- File paths are converted to lowercase before adding to `filePairs`.
- File pairs are retrieved using lowercase file paths.
By normalizing the file path case, the tool can successfully apply modifications regardless of the case used in the drive letters, which conforms with the expected behavior reported in the issue.
Closes #255.
Refer to devchat-ai/devchat#255 for more details on the reported issue.
> Fix Windows File Path Case Sensitivity Issue in Patch Application

- src/toolwrapper/devchat.ts
This PR introduces a significant simplification to the Devchat log insertion process by integrating the previously separate log insertion and HASH retrieval steps into a single unified action.
With this change, the `logInsert` method now returns an array of `LogEntry` objects, which includes the HASH value for each new log entry immediately upon insertion. This enhancement not only streamlines the development workflow but also leverages the updated capabilities of devchat-core, aiming to improve developer experience and efficiency.
Care has been taken to ensure backward compatibility, as existing code relying on the older implementation has been adapted to accommodate the new return structure.
By merging this PR, we will be closing the associated issue which suggested this improvement. …
> Streamline Log Insertion by Combining Insert and Retrieve Actions

- src/extension.ts
This PR addresses the issue where `commit.py` and other devchat subprocesses remained active even after closing Visual Studio Code, as reported in https://github.com/devchat-ai/devchat/issues/258. The changes ensure that all devchat-related processes are correctly terminated following the closure of the IDE.
- A `deactivate` function has been implemented to respond to IDE shutdown events.
- The `stopDevChatBase` method is now utilized to terminate all related subprocesses effectively.
- An import for the constants module has been added to support the termination process.
These amendments should mitigate the problem of resource occupation by orphaned subprocesses and enhance overall system performance and user experience.
Closes devchat-ai/devchat#258.
> Fix: Terminate Devchat Subprocesses After Closing VS Code

- src/extension.ts
This PR addresses an issue where devchat would fail to launch on Windows systems without administrator permissions due to missing configuration information. The changes include improved configuration checks, provision of default configurations for missing settings, and an update to the activation sequence to ensure better handling of uninitiated UI utilities.
By implementing these fixes, devchat can now launch successfully without the need for escalated privileges, improving the user experience for non-admin windows users.
The following improvements were made:
- Configuration retrieval now includes null checks to prevent failures.
- Default configurations are set when certain settings are missing.
- The UI utils initialization sequence has been modified to avoid activation errors. …
> Fix launch issue without admin permissions on Windows

- src/toolwrapper/devchat.ts
This pull request addresses the issue where an API key containing leading or trailing whitespaces could cause a misleading `openai.APIConnectionError`. By trimming whitespace from the `OPENAI_API_KEY`, we prevent the `h11._util.LocalProtocolError: Illegal header value` error and ensure that the key is in a valid format before initiating network requests, improving error clarity and user experience.
Closes devchat-ai/devchat#265
> Fix: Trim whitespace from OPENAI_API_KEY to prevent misleading 'APIConnectionError'

- src/extension.ts
This pull request addresses the issue where the plugin fails to initialize due to the inability to write to non-existent model data, particularly in specific versions of VSCode.
Changes include a try-catch block to handle configuration update calls gracefully during initialization. This ensures that plugin startup isn't halted by these exceptions. Additionally, any encountered errors are logged using `logger.channel()` to facilitate easier debugging and monitoring.
The proposed fix will skip the problematic data migration during initialization as a temporary measure until the new plugin version with internal configuration UI is released.
By merging this PR, we can ensure that the plugin remains functional across various versions of VSCode without disrupting the user experience.
Closes …
> Fix Plugin Initialization for Non-existent Model Data

- src/handler/chatHandler.ts
- src/handler/sendMessage.ts
This PR addresses the issue reported in https://github.com/devchat-ai/devchat/issues/293, where initiating multiple chat sessions simultaneously resulted in jumbled chat output. A check has been added to prevent a new chat command from being sent if a session is already in progress. Additionally, an error message is now displayed to the user if they attempt to send a second command while another is still active. This ensures that the chat output remains coherent and understandable as expected.
The following changes have been implemented:
- Check to prevent duplicate chat command execution
- Error message display for attempted re-executions via UiUtilWrapper
- Reset check after command execution completion
With these changes, users will no longer experience disruption in chat output when …
> Fix output disruption by preventing duplicate chat command execution

- src/contributes/codecomplete/promptCreator.ts
This pull request introduces an overall task context feature to the code completion engine as outlined in issue [#325](https://github.com/devchat-ai/devchat/issues/325). The changes are geared toward narrowing down the scope and improving the precision of code modification suggestions by considering the broader task the developer is working on.
- A new function `createTaskDescriptionContext` was added to gather the task description and context.
- The task description context is now incorporated into the prompting process for code completions, enhancing relevance and accuracy.
- The changes are aimed at enhancing developer productivity through more precise code completion suggestions.
By integrating a task-level context, we expect the suggestions provided by the code completion engine to …
> Implement Overall Task Context in Code Completion for Better Accuracy

- src/contributes/codecomplete/astIndex/createIdentifierSet.ts
This PR addresses an issue where files were getting indexed multiple times within the file indexing service, as reported in issue #326. The changes include:
- Initialization of FileBlockInfo early on to prevent re-indexing scenarios.
- A refactor of the createFileBlockInfo function which now returns an initialized object even on failure to ensure stability.
- Removal of extraneous FileBlockInfo instance creations to enhance code clarity and performance.
With these modifications, we should now see the expected behavior where each file is indexed a single time, eliminating duplicate entries and preventing any related performance or accuracy issues.
Closes https://github.com/devchat-ai/devchat/issues/326
> Fix: Resolve duplicate file indexing in File Index Service

- src/contributes/codecomplete/chunkFilter.ts
This PR introduces improvements to the line filtering process in the code completion feature:
- Lines that are empty or start with `)`, `]`, or `}` are now properly excluded from consideration.
- The chunk filtering logic has been optimized for enhanced accuracy in code completion results.
The adjustments should yield a smoother experience with more precise code completions.
> Fix: Improve line filtering logic for better code completion

- src/contributes/codecomplete/astIndex/index.ts
- src/contributes/codecomplete/codecomplete.ts
- src/contributes/codecomplete/llm.ts
- src/contributes/codecomplete/promptCreator.ts
- src/contributes/codecomplete/symbolindex/index.ts
- src/contributes/commands.ts
- src/contributes/commandsBase.ts
- src/extension.ts
- src/handler/configHandler.ts
- src/handler/historyMessagesHandler.ts
- src/ide_services/endpoints/ideLanguage.ts
- src/panel/statusBarView.ts
- src/toolwrapper/devchat.ts
- src/util/apiKey.ts
- src/util/config.ts
- src/util/feature_flags/feature_toggles.ts
- src/util/python_installer/install_devchat.ts
- test/util/config.test.ts
This pull request introduces the ability to switch between Nvidia Starcoder and Ollama Deepseek models for the code completion feature in Devchat. With this enhancement, users can seamlessly choose their preferred AI model for code completions to better suit their needs and preferences.
- Refactored the DevChatConfig instantiation to use the `getInstance()` method for better configuration management.
By merging this PR, users will gain more flexibility in their code completion experience.
Closes https://github.com/devchat-ai/devchat/issues/342
> Add support for switching between Nvidia Starcoder and Ollama Deepseek models

- src/util/config.ts
This PR addresses the problem reported in [#347](https://github.com/devchat-ai/devchat/issues/347) where Devchat fails to render correctly in VSCode if it has never been installed on the machine before. This was due to missing provider information that led to exceptions in the application flow.
- Ensuring that the configuration file is checked for existence and created if it does not exist.
- Parsing the configuration file into an object, even if it is initially empty, to prevent loading issues.
- Refactoring of configuration and value-setting logic to improve clarity and stability.
Additionally, subproject commit hashes have been updated in the GUI and tools directories to align with the latest changes.
Resolves devchat-ai/devchat#347.
> Fix initialization issue when Devchat is not previously installed in VSCode

- package.json
- src/panel/statusBarView.ts
In this pull request, two key changes have been made to improve the project's configuration and codebase:
1. The commit hash for the GUI submodule has been updated to integrate the latest changes.
2. The unnecessary DevChat installation commands for Python have been removed from the `package.json` and the corresponding execution lines in `statusBarView.ts` are commented out, ensuring that these commands are no longer triggered upon status bar item creation.
These changes streamline the project setup process and reduce potential for confusion or errors related to the DevChat install commands.
> Update GUI Submodule and Remove Unused DevChat Install Commands

- src/extension.ts
This PR addresses the issue where the API Base URL was being inadvertently set to a custom value for some users, causing an illegal API base error.
The changes include:
- Ensuring that the API base URL is correctly fixed to prevent the illegal base error
- Setting the default API base URL to https://api.devchat.ai/v1
- Invoking the fixDevChatApiBase function during the activate method to apply this fix
Closes devchat-ai/devchat#386
> Fix custom API Base URL causing illegal errors

- src/util/commonUtil.ts
This PR updates the logger message in spawnAsync function to truncate long commands and arguments for better readability and log management.
> chore: Truncate long commands in spawnAsync logger

- src/ide_services/services.ts
This small change updates the logger to use debug level instead of warn for better clarity during development.
> Update log level from warn to debug in services.ts

- src/handler/fileHandler.ts
- src/handler/handlerRegister.ts
- src/ide_services/endpoints/getCurrentFileInfo.ts
- src/ide_services/services.ts
feat: Add getCurrentFileInfo and getIDEServicePort handlers
- Added getCurrentFileInfo handler to retrieve the absolute path of the current file
- Added getIDEServicePort handler to retrieve the IDE service port
- Updated fileHandler.ts and handlerRegister.ts to include the new handlers
- Created getCurrentFileInfo.ts in ide_services/endpoints to implement the getCurrentFileInfo handler
- Updated services.ts in ide_services to include the getCurrentFileInfo handler
> feat: Add getCurrentFileInfo and getIDEServicePort handlers

- src/contributes/commands.ts
- src/contributes/quickFixProvider.ts
- src/ide_services/endpoints/documentRangeDiagnostics.ts
- src/ide_services/endpoints/getCollapsedCode.ts
- src/ide_services/endpoints/getToolsPath.ts
- src/ide_services/services.ts
This PR adds new IDE service endpoints and refactors the quick fix command implementation.
- Implementing getDiagnosticsInRange for code diagnostics
- Creating getCollapsedCode for code collapsing functionality
- Adding getExtensionToolsPath to retrieve tools directory
- Updating services.ts with new endpoint handlers
- Refactoring quick fix command to use document, range, and diagnostic
- Removing code collapsing and surrounding code extraction
- Updating command arguments to pass document, range, and diagnostic
These changes improve the functionality and efficiency of the IDE services and quick fix command.
> feat: Add new IDE service endpoints and refactor quick fix command

- src/contributes/codecomplete/llm.ts
This PR updates the stop tokens in the devchatComplete function to improve code completion behavior. The changes include:
- Removing "```" and "//" from the stop tokens list
- Retaining "<|endoftext|>", "<|EOT|>", "<file_sep>", and "\n\n" as stop tokens
- Adjusting the code completion behavior for improved results
These modifications aim to enhance the accuracy and effectiveness of the code completion functionality.
> feat: Update stop tokens in devchatComplete function

- src/toolwrapper/devchatClient.ts
This PR adds trace logging for the local service port in DevChatClient to enhance debugging capabilities for local service connections.
Changes:
- Add trace logging in DevChatClient constructor
- Implement logging in reset method
- Add logging in setLocalServicePort method
This improvement will help with troubleshooting and monitoring local service connections.
> feat: Add logging for local service port

- src/contributes/commands.ts
- Add safety check to remove existing workflow directory if present
- Ensure clean installation by removing old files before copying
- Prevent potential conflicts during version updates
> chore: Add cleanup for existing Merico workflow directory

- src/ide_services/services.ts
- Add new endpoint /get_extension_version to services registry
- Implement version fetch from package.json using vscode API
- Return undefined if extension is not found
- Update GUI submodule
> feat: Add extension version retrieval endpoint and update GUI submodule

- src/toolwrapper/devchatClient.ts
- Remove redundant baseURL checks in _get, _post, and chat methods
- Simplify port initialization logic for HTTP requests
- Consolidate error handling for missing service port configuration
> fix: Refactor service port handling in DevChatClient
